### ISSUE TITLE
AttributeError: 'State' object has no attribute 'output_ids_decoded'

### ISSUE THREAD

**Issue by jdg900** [IntelLabs/lvlm-interpret#6]
Hello.

Thank you for sharing your nice work!

I encountered an issue when I ran this command as follows:

```
python app.py --model_name_or_path Intel/llava-gemma-2b --load_8bit  --port 8080
```

```
Traceback (most recent call last):
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/blocks.py", line 1931, in process_api
    result = await self.call_function(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/SSD2/guest/jdgon/lvlm-interpret/utils_attn.py", line 68, in attn_update_slider
    fn_attention = state.attention_key + '_attn.pt'
AttributeError: 'State' object has no attribute 'attention_key'
Traceback (most recent call last):
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/blocks.py", line 1931, in process_api
    result = await self.call_function(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/blocks.py", line 1516, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/guest/.conda/envs/lvlm_inter/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/SSD2/guest/jdgon/lvlm-interpret/utils_causal_discovery.py", line 46, in causality_update_dropdown
    generated_text = state.output_ids_decoded
AttributeError: 'State' object has no attribute 'output_ids_decoded'
```

I just uploaded the image and input the text ("Describe this image as detailed as possible")

I'm looking forward to hearing from you as soon

Thank you

**Comment by jdg900** [comment]
Single GPU inference solved it.
Thank you !

**Comment by ZY123-GOOD** [comment]
I've encountered the same issue. Could you explain what might be causing this and how to resolve it? I'm indeed running the experiment on a single GPU, and I'm still experiencing this problem.

**Comment by jdg900** [comment]
> I've encountered the same issue. Could you explain what might be causing this and how to resolve it? I'm indeed running the experiment on a single GPU, and I'm still experiencing this problem.

Hello
At what stage did an error occur?

**Comment by ZY123-GOOD** [comment]
Thank you for your prompt response. I found that reinstalling the conda environment resolved the issue.



---Original---
From: "Donggon ***@***.***&gt;
Date: Thu, Aug 22, 2024 17:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IntelLabs/lvlm-interpret] AttributeError: 'State' object has noattribute 'output_ids_decoded' (Issue #6)




  
I've encountered the same issue. Could you explain what might be causing this and how to resolve it? I'm indeed running the experiment on a single GPU, and I'm still experiencing this problem.
  
Hello
 At what stage did an error occur?

**Comment by zhengyuan-xie** [comment]
> Thank you for your prompt response. I found that reinstalling the conda environment resolved the issue.
> […](#)
> ---Original--- From: "Donggon ***@***.***&gt; Date: Thu, Aug 22, 2024 17:59 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [IntelLabs/lvlm-interpret] AttributeError: 'State' object has noattribute 'output_ids_decoded' (Issue #6) I've encountered the same issue. Could you explain what might be causing this and how to resolve it? I'm indeed running the experiment on a single GPU, and I'm still experiencing this problem. Hello At what stage did an error occur? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Hi, could you share the information about your environment? Thanks!
